name: ç¼–è¯‘ledeæºç 
on:
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *
    
# coolsnowwolf
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  DIY_P3_SH: diy-part3.sh

  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: æ£€å‡ºæºç åˆ°workflows
      uses: actions/checkout@main
    - name: åˆå§‹åŒ–ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo -e "$(nproc) ä¸ªæ ¸å¿ƒç¼–è¯‘"      
        echo -e "é¦–æ¬¡åˆå§‹åŒ–ç¯å¢ƒå®Œæˆ,è¿è¡Œdf -Th å‘½ä»¤:"
        df -Th                
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL        
        echo -e "é¦–æ¬¡è¿è¡Œåˆ é™¤æ— ç”¨æ–‡ä»¶å‘½ä»¤,é¢„è®¡æ¸…ç†å®Œæˆåå¯ç”¨ç©ºé—´ä¸º37G.å·²å®Œæˆåˆ é™¤æ— ç”¨æ–‡ä»¶,è¿è¡Œdf -Th å‘½ä»¤:"
        df -Th          
        sudo docker image prune --all --force
        echo -e "ç¬¬äºŒæ¬¡è¿è¡Œåˆ é™¤æ— ç”¨dockeræ–‡ä»¶å‘½ä»¤,é¢„è®¡æ¸…ç†å®Œæˆåå¯ç”¨ç©ºé—´ä¸º40G.å·²å®Œæˆåˆ é™¤æ— ç”¨dockeré•œåƒ,è¿è¡Œdf -Th å‘½ä»¤:"
        df -Th        
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq full-upgrade -y
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: å…‹éš†æºä»£ç 
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b master openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        COMMIT_AUTHOR=$(git show -s --date=short --format="ä½œè€…: %an")
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
        COMMIT_DATE=$(git show -s --date=short --format="æ—¶é—´: %ci")
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
        COMMIT_MESSAGE=$(git show -s --date=short --format="å†…å®¹: %s")
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

    - name: åŠ è½½è‡ªå®šä¹‰è®¢é˜…æº
      run: |
        chmod +x $DIY_P1_SH
        cd openwrt
        #git checkout fac34a2dfe4e416c3d09e060503c671c9e8efe30
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: æ›´æ–°feedsè®¢é˜…æº
      run: cd openwrt && ./scripts/feeds update -a

    - name: å®‰è£…feedsè®¢é˜…æº
      run: cd openwrt && ./scripts/feeds install -a

    - name: åŠ è½½è‡ªå®šä¹‰é…ç½®çš„.shæ–‡ä»¶
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        chmod +x $DIY_P3_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
        $GITHUB_WORKSPACE/$DIY_P3_SH
    - name: ä¸‹è½½ dl åº“
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8

    - name: ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) ä¸ªæ ¸å¿ƒç¼–è¯‘"
        make -j$(nproc)
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        TZ="Asia/Shanghai" echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: æ£€æŸ¥ç£ç›˜ä½¿ç”¨æƒ…å†µ
      if: (!cancelled())
      run: df -hT

    - name: è¿›å…¥/bin/targetsç›®å½•ä¸‹,å…ˆåˆ é™¤packagesæ–‡ä»¶å¤¹,å†å°†å½“å‰è·¯å¾„å†™å…¥å˜é‡
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        ls -l
        rm -rf packages *initramfs-uImage* version.buildinfo *manifest
        echo -e "åˆ é™¤äº†packagesæ–‡ä»¶å¤¹ï¼Œå†è¿è¡Œ ll å‘½ä»¤:"
        ls -l
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV

    - name: ä¸Šä¼ /bin/targetsç›®å½•ä¸­çš„äº§ç‰©è‡³ Actions ä¸‹è½½é¡µ
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: ç”Ÿæˆå‘å¸ƒæ ‡ç­¾
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y-%m-%d_%H.%M")" >> $GITHUB_OUTPUT
        touch release_notes.txt
        echo "status=success" >> $GITHUB_OUTPUT
        echo "${{ github.event.inputs.release_notes }}" >> release_notes.txt
        echo "è®©æˆ‘ä»¬å†æ¥çœ‹çœ‹release_notes.txtä¸­æ˜¯ä»€ä¹ˆå†…å®¹:"
        echo "$(cat release_notes.txt)"

    - name: ä¸Šä¼ å›ºä»¶åˆ°release
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body: |
          **This is OpenWrt Firmware for Rockchip**
          ### ğŸ“’ å›ºä»¶ä¿¡æ¯
          - ğŸ’» å¹³å°æ¶æ„: rockchip-armv8 (rk35xx)ï¼ˆCyber 3588AIBï¼‰
          - âš½ å›ºä»¶æºç : ${{ env.REPO_URL }}
          - ğŸ’ æºç åˆ†æ”¯: master
          - ğŸš€ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL }}
          - ğŸŒ é»˜è®¤åœ°å€: 192.168.1.1
          - ğŸ”‘ é»˜è®¤å¯†ç : password
          ### ğŸ§Š å›ºä»¶ç‰ˆæœ¬
          - å›ºä»¶ç¼–è¯‘å‰æœ€åä¸€æ¬¡â¦[ä¸»æºç ](${{ env.REPO_URL }})æ›´æ–°è®°å½•
          - ${{ env.COMMIT_AUTHOR }}
          - ${{ env.COMMIT_DATE }}
          - ${{ env.COMMIT_MESSAGE }}
          - ${{ env.COMMIT_HASH }}
        #body_path: release_notes.txt
        files: ${{ env.FIRMWARE }}/*
